version: '3.4'
services:
  redditapione:
    image: productor_api
    command: /app/plumber.R
    restart: always
    ports:
     - "8002:8000"
    working_dir: /app
    volumes:
      - ./.env:/app/.Renviron
      - ./plumber.R:/app/plumber.R
      - ./notebooks:/app/notebooks
  redditapitwo:
    image: productor_api
    command: /app/plumber.R
    restart: always
    ports:
     - "8003:8000"
    working_dir: /app
    volumes:
      - ./.env:/app/.Renviron
      - ./plumber.R:/app/plumber.R
      - ./notebooks:/app/notebooks
  redditapithree:
    image: productor_api
    command: /app/plumber.R
    restart: always
    ports:
     - "8004:8000"
    working_dir: /app
    volumes:
      - ./.env:/app/.Renviron
      - ./plumber.R:/app/plumber.R
      - ./notebooks:/app/notebooks
  redditapifour:
    image: productor_api
    command: /app/plumber.R
    restart: always
    ports:
     - "8005:8000"
    working_dir: /app
    volumes:
      - ./.env:/app/.Renviron
      - ./plumber.R:/app/plumber.R
      - ./notebooks:/app/notebooks
  redditapifive:
    image: productor_api
    command: /app/plumber.R
    restart: always
    ports:
     - "8006:8000"
    working_dir: /app
    volumes:
      - ./.env:/app/.Renviron
      - ./plumber.R:/app/plumber.R
      - ./notebooks:/app/notebooks
